# permissions for end users to edit pgadmins.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: cloudnative-pg-kubebuilderv4
    app.kubernetes.io/managed-by: kustomize
  name: pgadmin-editor-role
rules:
- apiGroups:
  - postgresql.cnpg.io
  resources:
  - pgadmins
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - postgresql.cnpg.io
  resources:
  - pgadmins/status
  verbs:
  - get
